// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1024801674749:web:e81fb6133003cc4e473594',
    messagingSenderId: '1024801674749',
    projectId: 'registrationform-2c22d',
    authDomain: 'registrationform-2c22d.firebaseapp.com',
    storageBucket: 'registrationform-2c22d.appspot.com',
    measurementId: 'G-9V24DHJS7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:1024801674749:android:92761ec13d310f39473594',
    messagingSenderId: '1024801674749',
    projectId: 'registrationform-2c22d',
    storageBucket: 'registrationform-2c22d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:1024801674749:ios:d4b52957eed9a390473594',
    messagingSenderId: '1024801674749',
    projectId: 'registrationform-2c22d',
    storageBucket: 'registrationform-2c22d.appspot.com',
    iosBundleId: 'com.rs.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:1024801674749:ios:d4b52957eed9a390473594',
    messagingSenderId: '1024801674749',
    projectId: 'registrationform-2c22d',
    storageBucket: 'registrationform-2c22d.appspot.com',
    iosBundleId: 'com.rs.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:1024801674749:web:0c19b92e0354f0e4473594',
    messagingSenderId: '1024801674749',
    projectId: 'registrationform-2c22d',
    authDomain: 'registrationform-2c22d.firebaseapp.com',
    storageBucket: 'registrationform-2c22d.appspot.com',
    measurementId: 'G-D1F2NZMM2Q',
  );
}
